### ISSUE TITLE
Add Custom Marker Groups to organize certain custom marker colors

### ISSUE THREAD

**Issue by RoCris12** [SirJain0/CustomMarkerColors#8]
Make a way to put custom marker colors inside a custom marker color group to organize your custom marker colors so it doesn't look like a mess of a bunch of colors.

**Comment by SirJain0** [comment]
Would simply leaving a divider between default and custom colors work?

**Comment by RoCris12** [comment]
Well not really because when you have too much custom marker colors, even divided from default and custom colors, the custom color side will be kind of a mess when u have a lot of them.

**Comment by SirJain0** [comment]
Sorry, I don't think this is necessary.

**Comment by SirJain0** [comment]
I've added a dashboard to edit marker colors which should indirectly solve this issue.
